### ISSUE TITLE
Incompatible with Wynntils v1.1 even as of fuy v1.3.4

### ISSUE THREAD

**Issue by Gogetaaaa** [Essentuan/fuy.gg#14]

**Comment by rune0018** [comment]
update your wynntils
fuy.gg auto updates
incase this is related to not being able to launch

https://modrinth.com/mod/wynntils/

if its not then descripe where and what u are having truble with
@Gogetaaaa

**Comment by Essentuan** [comment]
this SHOULD be fixed as of 1.3.5, but I *may* have forgotten to upload to modrinth
