### ISSUE TITLE
what the hell is Buster

### ISSUE THREAD

**Issue by EnderNon** [Essentuan/fuy.gg#20]
where documentation

**Comment by Essentuan** [comment]
https://github.com/Essentuan/Buster

**Comment by EnderNon** [comment]
great thanks

also buster is busted rn it keeps trying to reconnect then failing to do so for me and co.

**Comment by Essentuan** [comment]
> great thanks
> 
> also buster is busted rn it keeps trying to reconnect then failing to do so for me and co.

are you on the latest version of fuy?

If not could you enable buster and post your latest.log here

**Comment by EnderNon** [comment]
mod was outdated my bad

**Comment by EnderNon** [comment]
ok i went through the buster code and i still cannot figure out what buster does

**Comment by Essentuan** [comment]
Its only used right now for warring, you can look at the packets in that repo to see exactly where its used.

**Comment by EnderNon** [comment]
> Its only used right now for warring, you can look at the packets in that repo to see exactly where its used.

where's the privacy policy on this about your collected data and where do i send a gdpr request
