### ISSUE TITLE
disabling configs without asking user

### ISSUE THREAD

**Issue by EnderNon** [Essentuan/fuy.gg#21]
https://www.youtube.com/watch?v=06sNBPPU8yM

fuy.gg is disabling the Wynntils raid display for its own without asking the user (big bad no no)

**Comment by Essentuan** [comment]
> https://www.youtube.com/watch?v=06sNBPPU8yM
> 
> fuy.gg is disabling the Wynntils raid display for its own without asking the user (big bad no no)

It disables it by default because it replaces the feature. Most people I've helped with fuy on my own have no idea how to disable overlays, and are always just confused by having two overlays doing basically the same thing. It only disables the features the first time you launch with fuy.gg. (I suppose it also could if your fuy config got corrupted)

**Comment by EnderNon** [comment]
it's clearly redisabling it after a restart of the client though. Also, editing files without user consent just screams odd.

**Comment by Essentuan** [comment]
Ok there was a problem here (it was in the config though that just happened to cause this issue). Fixed in 2.1.6

**Comment by Essentuan** [comment]
> it's clearly redisabling it after a restart of the client though. Also, editing files without user consent just screams odd.

I don't care really if it seems odd, this behavior leads to a significantly better user experience. We're here to improve their lives not make it worse. The community consensus around Wynntils is that its way too bloated because of whats enabled *by default*.

**Comment by EnderNon** [comment]
> We're here to improve their lives not make it worse

the fuygg raid overlay is actively worse than the wynntils one

- no damage counting
- weird time counting (counts some of the in between times unlike wynntils)

**Comment by Essentuan** [comment]
> > We're here to improve their lives not make it worse
> 
> the fuygg raid overlay is actively worse than the wynntils one
> 
>     * no damage counting
> 
>     * weird time counting (counts some of the in between times unlike wynntils)

For people who care about their PBs tracking time in the buff rooms IS important. Otherwise most people don't care. And why would I implement damage numbers for rooms when they're never gonna be accurate to what wynncraft says because of the damage scaling? Neither Wynncraft or Wynntils are gonna be very accurate (Wynncraft is gonna be a little more accurate in comparing the usefulness of a dps at least) and who cares about damage done outside of the boss?

**Comment by EnderNon** [comment]
> For people who care about their PBs tracking time in the buff rooms IS important. Otherwise most people don't care.

The issue is that there's not exactly a standard for this. But more people are going to be using Wynntils than Fuy.gg and thus most would compare by the Wynntils times.

> And why would I implement damage numbers for rooms when they're never gonna be accurate to what wynncraft says because of the damage scaling? Neither Wynncraft or Wynntils are gonna be very accurate (Wynncraft is gonna be a little more accurate in comparing the usefulness of a dps at least)

It would be a feature. Not accurate, but still an actual feature that's missing in fuy. I say wynntils is bloated as fuck but this is a useful feature for roughly comparing my build's damage with other players.

**Comment by Essentuan** [comment]
> > For people who care about their PBs tracking time in the buff rooms IS important. Otherwise most people don't care.
> 
> The issue is that there's not exactly a standard for this. But more people are going to be using Wynntils than Fuy.gg and thus most would compare by the Wynntils times.
> 
> > And why would I implement damage numbers for rooms when they're never gonna be accurate to what wynncraft says because of the damage scaling? Neither Wynncraft or Wynntils are gonna be very accurate (Wynncraft is gonna be a little more accurate in comparing the usefulness of a dps at least)
> 
> It would be a feature. Not accurate, but still an actual feature that's missing in fuy. I say wynntils is bloated as fuck but this is a useful feature for roughly comparing my build's damage with other players.

Neither of these problems particularly matter to me really. Everyone I've talked to prefers the way fuy does it ¯\_(ツ)_/¯
