### ISSUE TITLE
Fuy disabling wynntils on prism (and i think multimc too then)

### ISSUE THREAD

**Issue by enzomtpYT** [Essentuan/fuy.gg#22]
To reproduce:
- Download Prism
- Create new 1.21.1 instance with fabric
- Install fuy & wynntils
- Start game
- Close game
- Notice wynntils got disabled and won't launch if some mods needs a dependence
![NVIDIA_Overlay_SZtYTJBFeZ](https://github.com/user-attachments/assets/732b1dec-6750-4780-ab15-5ca54dae704f)

**Comment by Essentuan** [comment]
This is intended behavior. Fuy updates wynntils (and itself) on start up so it will disable Wynntils and use its own downloaded version. 

You have 2 options: 

1) Move wynnventory to `.minecraft/assets/custom`. 

2) Open fuy.gg's config, go to the 'Loader' tab, and disable this option.
![image](https://github.com/user-attachments/assets/850465c0-b36e-4c5c-9e22-6bfc2d3bb728)

**Comment by enzomtpYT** [comment]
I chose to go by option 1 thanks!
